### ISSUE TITLE
pip install cannot find tkinter and char_stuido

### ISSUE THREAD

**Issue by BcomedianC** [ldantas05/twitter_nlp#2]
Hi Idantas! This is Buyuan Lin doing the code review.
 All the aspects mentioned during the class seems great. 
However, it seems like package tkinter and char_stuido cannot be found by pip install command. It could be my environment's problem.
 Anyway, I think the code is wonderful! And I do apologize for my code may not run properly because my computer was broken and it's still not fixed yet. 
Thank you very much!

**Comment by ldantas05** [comment]
Hi Buyuan, tkinter is a library that is included with python so there is no need to pip install it. Make sure you are running python3. Char_studio is a typo it is chart_studio which is needed by plotly. Let me know if anything else is not running smoothly.
